test: script

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -31,10 +31,10 @@ jobs:
           cache: "yarn"
 
       - name: 📦 Install Dependencies
-        run: yarn install
+        run: yarn install --immutable
 
       - name: 🛠 Build the Package
-        run: yarn build 2>&1 || (echo "Build failed, running tsc directly for diagnostics:" && yarn tsc --project tsconfig.json --noEmit && exit 1)
+        run: yarn build 2>&1 || (echo "Build failed, running tsc directly for diagnostics:" && npx tsc --project tsconfig.json --noEmit && exit 1)
 
       # - name: 🔐 Setup .npmrc for release
       #   run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
